// Generated by CoffeeScript 1.10.0
(function() {
  canvas;
  var printToken;

  window.draw = function(location, song, state) {
    var canvas, cstring, i, j, k, len, len1, len2, line, lyric, ref, ref1, token;
    canvas = $(location);
    cstring = '';
    cstring += "<div class='panel panel-info'><div class='panel-heading'>" + song.meta.TITLE + "<br/><small>" + song.meta.ARTIST + "</small></div><div class='panel-body'>";
    ref = song.lyrics;
    for (i = 0, len = ref.length; i < len; i++) {
      lyric = ref[i];
      if (state.showSections) {
        cstring += "<div class='section'>" + lyric.section + "</div><br/>";
      }
      ref1 = lyric.lines;
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        line = ref1[j];
        for (k = 0, len2 = line.length; k < len2; k++) {
          token = line[k];
          cstring += printToken(token, state);
        }
        cstring += "<br/>";
      }
      cstring += "<br/>";
    }
    cstring += "</dl>";
    cstring += "</div></div>";
    canvas.html(cstring);
    return null;
  };

  printToken = function(token, state) {
    var chString, chord, pString, result, string;
    chord = token.chord == null ? ' ' : token.chord;
    string = token.string === '' ? ' ' : token.string.trim();
    pString = 'phrase';
    pString += token.wordExtension ? ' join' : '';
    result = '';
    result += "<p class=\"" + pString + "\">";
    if (state.showChords) {
      chString = 'chord';
      if (state.smartMode) {
        chString += token.exception ? '' : ' mute';
      }
      result += "<span class=\"" + chString + "\">" + chord + "</span><br/>";
    }
    result += "<span class='string'>" + string + "</span>";
    result += "</p>";
    return result;
  };

}).call(this);
