// Generated by CoffeeScript 1.10.0
(function() {
  var example, file, location;

  location = '#canvas';

  file = '';

  example = '##TITLE   I Wanna Hold Your Hand\n##ARTIST  The Beatles\n##ALBUM   A Hard Day\'s Night\n\n#INTRO\n: G D Em Bm\n\n#VERSE\n:       G\'             D          Em               E7    Bm\'\nOh yeah ^I\'ll tell you ^something ^ I think you\'ll ^under^stand\n:    G           D           Em                     B7\nWhen ^I say that ^something, ^ I want to hold your h^and!\n\n#CHORUS\n:C         D          G  Em  \n^ I wanna ^hold your ^ha^nd!\n:C         D          G      \n^ I wanna ^hold your ^hand!\n\n#VERSE\nOh ^please say to ^me, ^ you\'ll let me ^be your ^man\n:  *              G    *                          *\nOh ^please say to ^me, ^ you\'ll let me hold your h^and\n\n#CHORUS\n^Now let me ^hold your ^ha^nd\n^ I wanna ^hold your ^hand\n\n#BRIDGE\n:Dm           G                 C        Am        \n^ And when I ^touch you I feel ^happy in^side\n:Bm\'\'          G                C              D   \n^ It\'s such a ^feeling that my ^love, I can\'t ^hide\n:C         D                                       \n^ I can\'t ^hide\n:C         D                                       \n^ I can\'t ^hide\n\n#VERSE\nYeah-ah ^you, got that ^something ^ I think you\'ll under^stand.\nWhen ^I feel that ^something, ^ I wanna hold your ^hand.\n\n#CHORUS\n^ I wanna ^hold your ^ha^and!\n^ I wanna ^hold your ^hand!\n\n###\nG\' => Gsus4\nBm\'  => Bm7#11, Bmaj7\nBm\'\' => Dm';

  $(function() {
    var refresh, state;
    state = {
      showChords: true,
      showRepeats: false,
      showAlts: true,
      showSections: true,
      smartMode: true,
      requestedKey: null
    };
    refresh = function() {
      file = parser.parseString($('#input').val());
      console.log(file);
      draw(location, file, state);
      return $('.alts a').click(function() {
        var id;
        id = $(this).parent().attr('data-id-from');
        return $("span[data-id-to='" + id + "']").html($(this).html());
      });
    };
    $('#input').val(example);
    refresh();
    $('#input').keyup(refresh);
    $('#transposeUp').click(function() {
      state.requestedKey = createNote($('#currentKey').html()).sharp().clean().name;
      return refresh();
    });
    $('#transposeDown').click(function() {
      state.requestedKey = createNote($('#currentKey').html()).flat().clean().name;
      return refresh();
    });
    $('#transposeReset').click(function() {
      state.requestedKey = null;
      $('#transposeModal').modal('hide');
      return refresh();
    });
    $('#transposeToolbar button').click(function() {
      var clickedChord;
      clickedChord = $(this).attr('data-transposeChord');
      state.requestedKey = clickedChord;
      $('#transposeModal').modal('hide');
      return refresh();
    });
    $("[name='toggle-chords']").on('switchChange.bootstrapSwitch', function(event, bool) {
      state.showChords = bool ? true : false;
      if (!bool) {
        $("input[name='toggle-muted']").bootstrapSwitch('state', false);
        $("input[name='toggle-alts']").bootstrapSwitch('state', false);
      }
      return refresh();
    });
    $("[name='toggle-muted']").on('switchChange.bootstrapSwitch', function(event, bool) {
      state.smartMode = bool ? true : false;
      return refresh();
    });
    $("[name='toggle-section']").on('switchChange.bootstrapSwitch', function(event, bool) {
      state.showSections = bool ? true : false;
      return refresh();
    });
    $("[name='toggle-alts']").on('switchChange.bootstrapSwitch', function(event, bool) {
      state.showAlts = bool ? true : false;
      return refresh();
    });
    $("[name='toggle-edit']").on('switchChange.bootstrapSwitch', function(event, bool) {
      if (bool) {
        $('#input').parent().show();
      } else {
        $('#input').parent().hide();
      }
      if (bool) {
        $('#output').addClass('col-sm-6');
      } else {
        $('#output').removeClass('col-sm-6');
      }
      return refresh();
    });
    return $("input.bs").bootstrapSwitch();
  });

}).call(this);
